spring:
  application:
    name: user
  datasource:
    url: jdbc:postgresql://localhost:5435/ms-user-ms
    username: postgres-user
    password: postgres-password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  rabbitmq:
    addresses: amqps://collie.lmq.cloudamqp.com
    username: jskyccxh
    password: UbxAcQH0XqwCtUlfXyobOxBEtfZY8MU5
    virtual-host: jskyccxh

server:
  port: 8081